language: go
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- ./test.sh && ./build.sh && ./acceptance.sh
- GOPATH="$GOPATH:`pwd`/vendor:`pwd`" $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN || true
go:
- '1.3'
- '1.4'
- 'tip'
env:
  global:
    secure: c56xrj8EDAs3r/A4fvMF4sL1zQ/LpWTY9XTUjEdN33L+JBUlJeeDsnhtlNJ3KXFBbmdNFqJHt60Z3/AKp0UekCK1+aLjAdQww47fsqZakXEnmpxeZvFhUkOTFm96bna9EYnC4W5k9S3PfRGovlKHKVCk204ai2EKXFdi6kZjxo8=
